spring:
  application:
    name: url-shortener

  datasource:
    url: jdbc:postgresql://localhost:5433/url_shortener
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

app:
  base-url: http://localhost:8081

logging:
  level:
    root: INFO
    com.ptmharsha.urlshortener: DEBUG
